/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ling_jiboserialport_SerialPortUtil */

#ifndef _Included_com_ling_jiboserialport_SerialPortUtil
#define _Included_com_ling_jiboserialport_SerialPortUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ling_jiboserialport_SerialPortUtil
 * Method:    getSerialNumber
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ling_jiboserialport_SerialPortUtil_getSerialNumber
  (JNIEnv *, jclass);

/*
 * Class:     com_ling_jiboserialport_SerialPortUtil
 * Method:    setSerialNumber
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ling_jiboserialport_SerialPortUtil_setSerialNumber
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ling_jiboserialport_SerialPortUtil
 * Method:    turnLeft
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ling_jiboserialport_SerialPortUtil_turnLeft
  (JNIEnv *, jclass);

/*
 * Class:     com_ling_jiboserialport_SerialPortUtil
 * Method:    turnRight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ling_jiboserialport_SerialPortUtil_turnRight
  (JNIEnv *, jclass);

/*
 * Class:     com_ling_jiboserialport_SerialPortUtil
 * Method:    forward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ling_jiboserialport_SerialPortUtil_forward
  (JNIEnv *, jclass);

/*
 * Class:     com_ling_jiboserialport_SerialPortUtil
 * Method:    goback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ling_jiboserialport_SerialPortUtil_goback
  (JNIEnv *, jclass);

/*
 * Class:     com_ling_jiboserialport_SerialPortUtil
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ling_jiboserialport_SerialPortUtil_stop
  (JNIEnv *, jclass);

/*
 * Class:     com_ling_jiboserialport_SerialPortUtil
 * Method:    moveHand
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ling_jiboserialport_SerialPortUtil_moveHand
  (JNIEnv *, jclass);

/*
 * Class:     com_ling_jiboserialport_SerialPortUtil
 * Method:    moveBarrier
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ling_jiboserialport_SerialPortUtil_moveBarrier
  (JNIEnv *, jclass);

/*
 * Class:     com_ling_jiboserialport_SerialPortUtil
 * Method:    openLight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ling_jiboserialport_SerialPortUtil_openLight
  (JNIEnv *, jclass);

/*
 * Class:     com_ling_jiboserialport_SerialPortUtil
 * Method:    closeLight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ling_jiboserialport_SerialPortUtil_closeLight
  (JNIEnv *, jclass);

/*
 * Class:     com_ling_jiboserialport_SerialPortUtil
 * Method:    setSpeedLeft
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ling_jiboserialport_SerialPortUtil_setSpeedLeft
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ling_jiboserialport_SerialPortUtil
 * Method:    setSpeedRight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ling_jiboserialport_SerialPortUtil_setSpeedRight
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
